---
title: Norma Camacho
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
site: Portfolio
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
paginate: 6
paginate_path: "/blog/page:num/"
