---
title: Norma Camacho
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://normasweb.link/
baseurl: 
email: your-email@domain.com
description: 'Norma's Portfolio Website

'
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
paginate: 3
paginate_path: blog/page:num
