---
title: Norma Camacho
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
site: Portfolio
markdown: 
kramdown: 
sass:
  style: compressed
plugins: 
paginate: 6
paginate_path: 
